[package]
name = "fabric-writer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
genco = "0.19"
anyhow = "1"
heck = "0.5.0"
which = "8"

[dev-dependencies]
tempfile = "3"
dotenvy = "0.15"
serial_test = "4"
