use crate::java_codegen::JavaCodegen;
use crate::state::ModState;
use crate::state::{Item, ItemKind};
use anyhow::Context;
use genco::prelude::*;
use std::path::PathBuf;

fn to_upper(id: &str) -> String {
    id.to_uppercase().replace('-', "_")
}

fn item_properties(item: &Item) -> java::Tokens {
    let mut out: java::Tokens = quote! { new Item.Properties() };

    if item.kind == ItemKind::Tool {
        if let Some(ref mat) = item.material {
            let snippet = format!(
                "sword({}, {}, {})",
                mat,
                item.attack_damage.unwrap_or(1.0),
                item.attack_speed.unwrap_or(1.6)
            );
            quote_in! { out => .$(snippet) }
        }
    }

    if let Some(dur) = item.durability {
        let snippet = format!("durability({})", dur);
        quote_in! { out => .$(snippet) }
    }

    out
}

pub(crate) fn write_mod_item_ids(
    path: &PathBuf,
    state: &ModState,
    codegen: &JavaCodegen,
) -> anyhow::Result<()> {
    let registries = &codegen.registries;
    let identifier = &codegen.identifier;
    let resource_key = &codegen.resource_key;
    let item = &codegen.item;

    let ns = state.mod_name.as_str().to_lowercase();
    let mod_namespace = quoted(&ns);

    let t: java::Tokens = quote! {
        $("// GENERATED BY FABRIC-WRITER — DO NOT MODIFY")$['\r']
        $("// ")$['\r']
        public class ModItemIds {
            public static $resource_key<$item> create(String name) {
                return $resource_key.create($registries.ITEM, $identifier.fromNamespaceAndPath($mod_namespace, name));
            }

            $("// Item Resource Keys")
            $(for i in &state.items =>
                public static final $resource_key<$item> $(to_upper(&i.id)) = create($(quoted(i.id.as_str()))); $['\r']
            )
        }
    };

    JavaCodegen::write(path, t, state.package_name.as_str())
}

pub(crate) fn write_mod_items(
    path: &PathBuf,
    state: &ModState,
    codegen: &JavaCodegen,
) -> anyhow::Result<()> {
    let function = &codegen.function;
    let registry = &codegen.registry;
    let built_in_registries = &codegen.built_in_registries;
    let resource_key = &codegen.resource_key;
    let item = &codegen.item;

    let t: java::Tokens = quote! {
        $("// GENERATED BY FABRIC-WRITER — DO NOT MODIFY")$['\r']
        $("// ")$['\r']
        public class ModItems {
            public static $item register($resource_key<$item> itemKey, $function<$item.Properties, $item> itemFactory, $item.Properties settings) {
                $item item = itemFactory.apply(settings.setId(itemKey));
                $registry.register($built_in_registries.ITEM, itemKey, item);
                return item;
            }

            public static void initialize() {}

            $("// Item Registration")
            $(for i in &state.items =>
                public static final $item $(to_upper(&i.id)) = register(ModItemIds.$(to_upper(&i.id)), $item::new, $(item_properties(i)));$['\r']
            )
        }
    };

    JavaCodegen::write(path, t, state.package_name.as_str())
}

pub(crate) fn write_main_mod_class(
    path: &PathBuf,
    state: &ModState,
    codegen: &JavaCodegen,
) -> anyhow::Result<()> {
    let mod_class = state.mod_name.as_str();
    let mod_id = state.mod_id.as_str();

    let mod_initializer = &codegen.mod_initializer;
    let identifier = &codegen.identifier;
    let logger = &codegen.logger;
    let logger_factory = &codegen.logger_factory;

    let t: java::Tokens = quote! {
        $("// GENERATED BY FABRIC-WRITER — DO NOT MODIFY")$['\r']
        $("// ")$['\r']
        public class $mod_class implements $mod_initializer {
            public static final String MOD_ID = $(quoted(mod_id));

            public static final $logger LOGGER = $logger_factory.getLogger(MOD_ID);

            @Override
            public void onInitialize() {
                LOGGER.info("Hello Fabric world!");

                $("// Initializing items")
                ModItems.initialize();
                ModBlocks.initialize();
            }

            public static $identifier id(String path) {
                return $identifier.fromNamespaceAndPath(MOD_ID, path);
            }
        }
    };

    JavaCodegen::write(path, t, state.package_name.as_str())
}

pub(crate) fn write_lang_provider(
    path: &PathBuf,
    state: &ModState,
    codegen: &JavaCodegen,
) -> anyhow::Result<()> {
    let fabric_pack_output = &codegen.fabric_pack_output;
    let fabric_language_provider = &codegen.fabric_language_provider;
    let holder_lookup = &codegen.holder_lookup;
    let completable_future = &codegen.completable_future;

    let t: java::Tokens = quote! {
        $("// GENERATED BY FABRIC-WRITER — DO NOT MODIFY")$['\r']
        $("// ")$['\r']
        public class LangProvider extends $fabric_language_provider {
            protected LangProvider($fabric_pack_output dataOutput, $completable_future<$holder_lookup.Provider> registryLookup) {
                super(dataOutput, "en_us", registryLookup);
            }

            @Override
            public void generateTranslations($holder_lookup.Provider holderLookup, TranslationBuilder translationBuilder) {
                $(for i in &state.items =>
                    translationBuilder.add($(quoted("item.".to_owned() + &state.mod_id.as_str() + "." + i.id.as_str())), $(quoted(to_upper(&i.id))));$['\r']
                )
                $(for b in &state.blocks =>
                    translationBuilder.add($(quoted("block.".to_owned() + &state.mod_id.as_str() + "." + b.id.as_str())), $(quoted(to_upper(&b.id))));$['\r']
                )
            }
        }
    };

    JavaCodegen::write(
        path,
        t,
        &(state.package_name.as_str().to_owned() + ".client"),
    )
}

pub(crate) fn write_datagen_entrypoint(
    path: &PathBuf,
    state: &ModState,
    codegen: &JavaCodegen,
) -> anyhow::Result<()> {
    let mod_generator_class = format!("{}DataGenerator", state.mod_name.as_str());

    let data_generator_entrypoint = &codegen.data_generator_entrypoint;
    let fabric_data_generator = &codegen.fabric_data_generator;

    let t: java::Tokens = quote! {
        $("// GENERATED BY FABRIC-WRITER — DO NOT MODIFY")$['\r']
        $("// ")$['\r']
        public class $mod_generator_class implements $data_generator_entrypoint {
            @Override
            public void onInitializeDataGenerator($fabric_data_generator fabricDataGenerator) {
                $fabric_data_generator.Pack pack = fabricDataGenerator.createPack();

                pack.addProvider(LangProvider::new);
                pack.addProvider(ModelProvider::new);
            }
        }
    };

    JavaCodegen::write(
        path,
        t,
        &(state.package_name.as_str().to_owned() + ".client"),
    )
}

pub(crate) fn write_model_provider(
    path: &PathBuf,
    state: &ModState,
    codegen: &JavaCodegen,
) -> anyhow::Result<()> {
    let fabric_model_provider = &codegen.fabric_model_provider;
    let model_templates = &codegen.model_templates;
    let fabric_pack_output = &codegen.fabric_pack_output;

    let t: java::Tokens = quote! {
        $("// GENERATED BY FABRIC-WRITER — DO NOT MODIFY")$['\r']
        $("// ")$['\r']
        public class ModelProvider extends $fabric_model_provider {
            protected ModelProvider($fabric_pack_output dataOutput) {
                super(dataOutput);
            }

            @Override
            public void generateItemModels() {
                $(for i in &state.items =>
                    generateFlatItem(ModItems.$(to_upper(&i.id)), $model_templates.FLAT_ITEM);$['\r']
                )
                $(for b in &state.blocks =>
                    generateBlock(ModBlocks.$(to_upper(&b.id)), $model_templates.CUBE_ALL);$['\r']
                )
            }
        }
    };

    JavaCodegen::write(
        path,
        t,
        &(state.package_name.as_str().to_owned() + ".client"),
    )
}

pub(crate) fn write_mod_blocks(
    path: &PathBuf,
    state: &ModState,
    codegen: &JavaCodegen,
) -> anyhow::Result<()> {
    let block = &codegen.block;
    let block_item = &codegen.block_item;
    let block_behaviour = &codegen.block_behaviour;
    let built_in_registries = &codegen.built_in_registries;
    let resource_key = &codegen.resource_key;
    let identifier = &codegen.identifier;
    let item = &codegen.item;

    let ns = state.mod_name.as_str().to_lowercase();
    let mod_namespace = quoted(&ns);

    let t: java::Tokens = quote! {
        $("// GENERATED BY FABRIC-WRITER — DO NOT MODIFY")$['\r']
        $("// ")$['\r']
        public class ModBlocks {
            $(for b in &state.blocks =>
                public static final $block $(to_upper(&b.id)) = $built_in_registries.BLOCK.register(
                    $resource_key.create($identifier.fromNamespaceAndPath($mod_namespace, b.id.as_str())),
                    new $block(new $block_behaviour.Properties())
                );$['\r']
                public static final $block_item $(to_upper(&b.id))_ITEM = $built_in_registries.ITEM.register(
                    $resource_key.create($identifier.fromNamespaceAndPath($mod_namespace, b.id.as_str())),
                    new $block_item($(to_upper(&b.id)), new $item.Properties())
                );$['\r']
            )

            public static void initialize() {}
        }
    };

    JavaCodegen::write(path, t, state.package_name.as_str())
}

pub(crate) fn regenerate_all(state: &ModState) -> anyhow::Result<()> {
    let java_root = PathBuf::from("src/main/java").join(state.package_name.replace('.', "/"));
    let client_root = PathBuf::from("src/client/java").join(state.package_name.replace('.', "/"));
    std::fs::create_dir_all(&java_root).context("Failed to create Java source directory")?;
    std::fs::create_dir_all(&client_root)
        .context("Failed to create client Java source directory")?;

    let codegen = JavaCodegen::new();

    write_mod_item_ids(&java_root.join("ModItemIds.java"), state, &codegen)?;
    write_mod_items(&java_root.join("ModItems.java"), state, &codegen)?;
    write_main_mod_class(
        &java_root.join(format!("{}.java", state.mod_name)),
        state,
        &codegen,
    )?;
    write_lang_provider(
        &client_root.join("client/LangProvider.java"),
        state,
        &codegen,
    )?;
    write_datagen_entrypoint(
        &client_root.join("client/DataGeneratorEntrypoint.java"),
        state,
        &codegen,
    )?;
    write_model_provider(
        &client_root.join("client/ModelProvider.java"),
        state,
        &codegen,
    )?;
    write_mod_blocks(&java_root.join("ModBlocks.java"), state, &codegen)?;

    Ok(())
}
